module CrawlerDev
  module Resources
    class Files
      def extract_text: (
        file: CrawlerDev::Internal::file_input,
        ?clean_text: bool,
        ?strip_boilerplate: bool,
        ?request_options: CrawlerDev::request_opts
      ) -> CrawlerDev::Models::FileExtractTextResponse

      def initialize: (client: CrawlerDev::Client) -> void
    end
  end
end
