module CrawlerDev
  module Resources
    class URLs
      def extract_text: (
        url: String,
        ?clean_text: bool,
        ?headers: ::Hash[Symbol, String],
        ?proxy: CrawlerDev::URLExtractTextParams::Proxy,
        ?request_options: CrawlerDev::request_opts
      ) -> CrawlerDev::Models::URLExtractTextResponse

      def initialize: (client: CrawlerDev::Client) -> void
    end
  end
end
