module CrawlerDev
  module Models
    type file_extract_text_params =
      { file: CrawlerDev::Internal::file_input, clean_text: bool }
      & CrawlerDev::Internal::Type::request_parameters

    class FileExtractTextParams < CrawlerDev::Internal::Type::BaseModel
      extend CrawlerDev::Internal::Type::RequestParameters::Converter
      include CrawlerDev::Internal::Type::RequestParameters

      attr_accessor file: CrawlerDev::Internal::file_input

      attr_reader clean_text: bool?

      def clean_text=: (bool) -> bool

      def initialize: (
        file: CrawlerDev::Internal::file_input,
        ?clean_text: bool,
        ?request_options: CrawlerDev::request_opts
      ) -> void

      def to_hash: -> {
        file: CrawlerDev::Internal::file_input,
        clean_text: bool,
        request_options: CrawlerDev::RequestOptions
      }
    end
  end
end
